# API server listen address
# Defauls to: ":8080" which will listen on all avalable interfaces.
# Overwrite with environment variable: DEVICECONNECT_LISTEN

listen: :8080

# NATS uri
# Defauls to: "nats://localhost:4222"
# Overwrite with environment variable: DEVICECONNECT_NATS_URI

nats_uri: "nats://mender-nats:4222"

# Mongodb connection string
# Defaults to: "mongodb://localhost"
# Overwrite with environment variable: DEVICECONNECT_MONGO_URL

mongo-url: mongodb://mender-mongo:27017

# Mongodb database name
# Defaults to: "deviceconnect"
# Overwrite with environment variable: DEVICECONNECT_MONGO_DBNAME

mongo-dbname: deviceconnect

# Enable SSL for mongo connections
# Defaults to: false
# Overwrite with environment variable: DEVICECONNECT_MONGO_SSL

# mongo_ssl: false

# SkipVerify controls whether a mongo client verifies the
# server's certificate chain and host name.
# If InsecureSkipVerify is true, accepts any certificate
# presented by the server and any host name in that certificate.
# Defaults to: false
# Overwrite with environment variable: DEVICECONNECT_MONGO_SSL_SKIPVERIFY

# mongo_ssl_skipverify: false

# Mongodb username
# Overwrites username set in connection string.
# Defaults to: none
# Overwrite with environment variable: DEVICECONNECT_MONGO_USERNAME

# mongo_username: user

# Mongodb password
# Overwrites password set in connection string.
# Defaults to: none
# Overwrite with environment variable: DEVICECONNECT_MONGO_PASSWORD

# mongo_password: secret
